name = "evx-cpr-qr-redirect"
main = "src/worker.ts"
compatibility_date = "2025-08-01"
account_id = "e04143feff1d545d4700b6406cccff9f"

routes = [
  { pattern = "cpr.evx.tech/public/cs/*", zone_name = "evx.tech" }
  ,{ pattern = "cpr.evx.tech/admin*", zone_name = "evx.tech" }
  ,{ pattern = "cpr.evx.tech/login", zone_name = "evx.tech" }
  ,{ pattern = "cpr.evx.tech/api/*", zone_name = "evx.tech" }
  ,{ pattern = "cpr.evx.tech/logout", zone_name = "evx.tech" }
  ,{ pattern = "cp.evx.tech/public/cs/*", zone_name = "evx.tech" }
]

[vars]
COUNTRY_CODE = "AU"
ADMIN_USERNAME = "admin"
ORIGIN_HOST = "evx.au.charge.ampeco.tech"

[[kv_namespaces]]
binding = "MAPPINGS"
id = "f9dbf6e141474a4b9e4fc035fc689c0b"
